# fly.toml app configuration file generated for drinkster on 2023-12-23T15:22:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "drinkster"
primary_region = "arn"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
